source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
#inhibit_all_warnings!
use_frameworks!

pod 'GoogleAnalytics-iOS-SDK', '~> 3.1'
pod 'youtube-ios-player-helper', '~> 0.1'
pod 'MWFeedParser', '~> 1.0'

pod 'Alamofire', '~> 1.2'
