source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!

pod 'GoogleAnalytics-iOS-SDK', '~> 3.1'
pod 'youtube-ios-player-helper', '~> 0.1'
pod 'MWFeedParser', '~> 1.0'
