source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'iCalcio' do

  pod 'Alamofire', '~> 3.1'
  pod 'youtube-ios-player-helper', '~> 0.1'
  pod 'MWFeedParser', '~> 1.0'
  pod 'GoogleAnalytics', '~> 3.1'

end